BASE_PORT=45000
TIMESLICE_SIZE=2046
IN_BUF_SIZE=30
CN_BUF_SIZE=25
HUGE_PAGES=2M
IN_PER_NODE=1
CN_PER_NODE=1


SCHEDULER_HISTORY_SIZE=10
SCHEDULER_INTERVAL_LENGTH=10000
SCHEDULER_VARIANCE_LIMIT=5
SCHEDULER_SPEEDUP_PERCENTAGE=25
SCHEDULER_SPEEDUP_INTERVAL_COUNT=10
LOG_DIRECTORY=/home/bemsalem/projects/fles_libfabric_DFS/build/jobs
ENABLE_LOGGING=true

USE_VERBS=1
